version: 0.2
phases:
    install:
        commands:
            - 'npm install'
artifacts:
    type: zip
    files:
        - Procfile
        - .platform/**/*
        - .npmrc
        - package.json
        - package-lock.json
        - 'src/**/*'
        - README.md
